# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0903569349663251b4fbc417cb36101cb5c7056dcc53f71a2b9d884cff6fa44d38088317a6a574fccd02e105c3d994f2a386085f560eccf27d7b6031365a8ad4

test:
  secret_key_base: 95cc33a6933375d487776634638da178828dc762ae3c52557c7df0da0bc02a9ab55f9e91096644c3a780ed4426a198e932825ecb7caf925c170a6a164a141357

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
